swagger: "2.0"
info:
  description: "Cloud Endpoints DNS"
  title: "Cloud Endpoints DNS"
  version: "1.0.0"
paths: {}
host: "frontend.endpoints.misc-project-317604.cloud.goog"
x-google-endpoints:
- name: "frontend.endpoints.misc-project-317604.cloud.goog"
  target: "34.149.29.248"
