apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: zone-ingress
  namespace: zoneprinter
  # annotations:
  # networking.gke.io/static-ip: <static-ip-here> # Your reserved IP address goes here 
spec:
  template:
    spec:
      backend:
        serviceName: zone-mcs
        servicePort: 8080