apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: hello-mcs
  namespace: sample
  # annotations:
    # beta.cloud.google.com/backend-config: '{"ports":{"default":"gke-ingress-config"}}'
spec:
  template:
    spec:
      selector:
        app: helloworld
      ports:
      - name: web
        protocol: TCP
        port: 5000
        targetPort: 5000